# Configuracion de servidor y aplicacion
server.port=${PORT:8080}
spring.application.name=urleads-backend

# Configuracion de base de datos PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de migraciones Flyway
spring.flyway.enabled=true

# Seguridad de la cookie de sesion JSESSIONID
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false
